### ISSUE TITLE
Request to add a License to the project

### ISSUE THREAD

**Issue by JayKaku** [ZipCPU/dblclockfft#12]
@ZipCPU could you please add a valid license to the project I can't really use it for an official purpose, I saw gpvl3 has been tagged into the topics for this repo but I am not sure that's the same as actually putting a license on github, so most likely I can't use it ig?

**Comment by ZipCPU** [comment]
As documented within the project:
1. The core generator software is released under GPLv3.
2. The IP generated is released under LGPLv3

You can find a copy of the LGPLv3 license in the doc/ directory as required for being distributed under LGPL.

Dan

**Comment by JayKaku** [comment]
My bad just saw it was inside the folder, thanks!
