### ISSUE TITLE
How would I use this FFT for my 20khz sampled audio signal?

### ISSUE THREAD

**Issue by Magmanat** [ZipCPU/dblclockfft#14]
I am using windows, but i use windows subsystem for linux (WSL) to make the fft program and also to generate my FFT's

I am using a BASYS3 board with 100MHz clock, I want my FFT to be able to bin the audio signal of 20Khz sampling to around a 20Hz frequency resolution Is it possible to get some guidance to use this?

./fftgen -f 1024 -n 12 -m 6 -p 20 -k 5000

these are the current commands i use to generate my FT as i believe that to have 20Hz binning resolution it is 20Khz / 1024 which gives me 20Hz bins. 

my pmod mic 3 outputs 12 bit data
and i have an oled screen that has 64 pixels in height hence i put the output in 6 bits to be able to map my output to the oled screen

-p 20 as i saw that BASYS3 has DSP elements and hence this is more efficient

-k 5000 as i am currently using my 100Mhz clock while pushing in the 20khz samples

is this the correct implementation? or am i doing something wrongly

**Comment by ZipCPU** [comment]
Sounds good.  Let me know how it works out for you.

Some insights you might wish to consider:
- The '-k 5000' is really pretty irrelevant.  The max value supported here is '-k 3'.  Larger numbers won't hurt though, so ... you are fine as you have it.
- When using '-m 6', you'll be throwing most of your PMIC bits away.  I'd be tempted to use '-m 12' and then only throw bits away at the end of the operation.
- If your goal is to detect the presence of a tone, you might wish to look into windowing, and/or oversampling.

Dan

**Comment by Magmanat** [comment]
1. Ahh that makes more sense... Hahaha i was wondering why my output did not change 
2. Sounds good, i will probably use 12 bits, find the abs and then bitshift it down back to 6 bits
3. Thanks for the heads up, for the moment i am crudely hardcoding notes into my program to detect, however i might need to use cents over a pitch method eventually, may i clarify that oversampling is just feeding my fft more points than my source?
For e.g. clocking my fft at 40Khz when my source is 20Khz

But overall, wow what an amazing tool you have built... Really saving my life here thanks!

**Comment by ZipCPU** [comment]
You might find [this article valuable](https://zipcpu.com/dsp/2020/11/21/spectrogram.html).  It explains some of the issues associated with overlap and oversampling.  You might also find [rudimentary logarithms](https://github.com/ZipCPU/fftdemo/blob/master/rtl/fft/logfn.v) to be valuable when trying to work with large dynamic ranges.

Good luck!

Dan
