### ISSUE TITLE
Support FP32 format

### ISSUE THREAD

**Issue by Oxygen-Chu** [ZipCPU/dblclockfft#7]
Is it possible to support single-precision floating-point format supported by Xilinx Versal?

**Comment by ZipCPU** [comment]
As currently written, could the dblclockfft IP core support floating point format?  I doubt it.  Could the core generator be rewritten for that purpose?  Perhaps.  I'll have to think through the implications.

I think one of the bigger problems will be the fact that adds would go from taking one cycle to many.  That would have a non-trivial affect on sequencing within the various sub-cores.

Dan
