### ISSUE TITLE
X propagation : 4096 pt FFT

### ISSUE THREAD

**Issue by mohdsamir93** [ZipCPU/dblclockfft#8]
4096 point FFT was created with input data width 4bits and output data width 4bits. Output(o_result) is showing x value through out.checked the waveform in detail , after the stage_4096 onwards 'x' is getting propagated through the FFT and at the end only value is coming as output.
[0.txt](https://github.com/ZipCPU/dblclockfft/files/6215444/0.txt)

Testbench 
`module main_tb();
reg clk;
reg ce;
reg rst;
//reg IN;
wire [7:0] result;
wire sync;
reg [7:0] sample;

//integer i=0;

fftmain dut(.i_clk(clk),
            .i_reset(rst),
            .i_ce(ce),
            .i_sample(sample),       
            .o_sync(sync),
            .o_result(result) 
             );

always #2 clk = ~ clk;

initial
     begin
	     $dumpfile("main.vcd");
             $dumpvars(0, main_tb);
     end

initial
    begin
           
      clk = 0;
      rst = 1;
      ce = 0;
       
    #6
       rst = 0;
       ce =1;
       $readmemb("0.txt",IN,0,1); 
       //IN <= 4'b1110;
   end    

always @(posedge clk )
   begin
    if (ce !=0)
    sample <= IN;
    

   sample <= IN[i];
    if (i != 1)
    i<= i+1;
   end  
initial
  begin
    #100 $finish;
    end  

 endmodule`

**Comment by ZipCPU** [comment]
The issue lies in your test bench.

1. Make sure you define IN before assigning sample to it
2. As a result, sample is 'x on the first clock tick
3. This problem is somewhat hidden by the delta cycle created by assigning to CE and RST separate from the clock tick.
4. I recommend, therefore, that you assign CE and RST as follows:
```
    initial begin // ...
        // $readmem belongs here ... but we'll keep it out of place so you can see the problem
        #6;
        rst <= 0;
        ce <= 1;
        @(posedge i_clk);
    end
```
Dan
